### ISSUE TITLE
Optimize min count sketch

### ISSUE THREAD

**Issue by piskvorky** [RaRe-Technologies/bounter#4]
- [x]  profile the existing implementation at line level
- [x] identify hotspots and higher-level usage patterns that will benefit from low-level optimization (loops, sequence updates)
- [x] optimize hotspots in C (or via Cython)
- [x] update setup.py to use a compiled extension

An important consideration is pushing the GIL locking as high up as possible (release GIL as early as possible). The idea to allow users to train multiple MinCountSketch objects independently, from multiple input streams in parallel, and then merge them at the end (see also #6).

**Comment by isamaru** [comment]
#10 Implements this

**Comment by piskvorky** [comment]
@isamaru tick off the checkboxes in description where done, and post info (link) about where to find the results of that particular step.

Which code parts are the bottlenecks, and what usage patterns affect the runtime the most, are critical pieces of information. They are relevant no matter what language is used for the implementation.

**Comment by isamaru** [comment]
I measured hotspots with a line profiler. Most relevant result that I got is this, but that's almost pure python:
[profile_results.txt](https://github.com/RaRe-Technologies/bounter/files/1292316/profile_results.txt)

It shows that:
1) There is no single bottleneck with the python implementation. Calculating hash, random number, accessing numpy table, HLL increase, and even the numerical operations are all in the same order of magnitude
2) the chosen language indeed does affect performance. Basic calculations should be significantly faster, 
python overhead dominates the time cost.
3) Depth is the parameter that drives performance most significantly, as it controls the number of iterations of the main loop. (Experiments with different depths confirmed that time was increasing linearly with depth)

After implementation of the algorithm and all its parts in C, the time dropped significantly, to the point where the test time is dominated by the outer python loop which feeds the values to the dictionary rather than the dictionary itself.

I would have to use different technologies to drill down into line-level of the C code, and I don't feel that is necessary.

**Comment by isamaru** [comment]
Some measurements with the C implementation:

```
from bounter import CountMinSketch as CMS
from timeit import default_timer as timer
from collections import Counter
iter = 10000000

for algorithm in ["conservative", "log1024", "log8"]:
        for depth in [2,4,6,8,16]:
                start = timer()
                c = CMS(depth=depth, width=1048576, algorithm=algorithm)
                for i in range(iter):
                        c.increment("foo")
                end = timer()
                print(algorithm, depth, end-start)

start = timer()
c = Counter()
for i in range(iter):
        c["foo"] += 1
end = timer()
print("Python Dictionary:", end-start)
```

> ('conservative', 2, 4.9088339008042094)
> ('conservative', 4, 5.363756528908515)
> ('conservative', 6, 5.687244434979469)
> ('conservative', 8, 5.845167688285299)
> ('conservative', 16, 7.547338702711116)
> ('log1024', 2, 5.097640911956059)
> ('log1024', 4, 5.573731871507832)
> ('log1024', 6, 6.016513958415118)
> ('log1024', 8, 6.256559698192731)
> ('log1024', 16, 7.869675844556596)
> ('log8', 2, 5.198647306801185)
> ('log8', 4, 5.511823664091452)
> ('log8', 6, 5.868493435384011)
> ('log8', 8, 6.281324862750736)
> ('log8', 16, 7.905160521132402)
> ('Python Dictionary:', 7.526680111492837)

**Comment by piskvorky** [comment]
Thanks. Is there a way we can avoid (minimize) that outer loop?

Some common usage pattern where we can drop to C faster?

**Comment by isamaru** [comment]
We do support cms.update() for lists or dictionaries which works fine but it's not optimized for C.

I have a C-optimized implementation for HashTable, I can modify it to work for CMS which shouldn't be too hard.

**Comment by piskvorky** [comment]
`update` should work on any iterable or mapping, not just lists and dictionaries.
